version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
  phppgadmin:
    image: zhajor/docker-phppgadmin
    depends_on:
      - db
    links:
      - db
    ports:
        - "8080:80"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  caluma:
    image: projectcaluma/caluma:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
      - LANGUAGES=de,fr,en
    volumes:
      - ./dumps:/app/dumps
