version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
  caluma:
    image: projectcaluma/caluma:latest@sha256:17372b215a878db242459c3b4fef61a398d561bf71ff9ddf01457e6c89e59109
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
