version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data

  caluma:
    image: projectcaluma/caluma:latest@sha256:a97ced8e8f675c01cc0a26997a64b2facff847490966dd39a79be6a78ee7408a
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
      #- MINIO_STORAGE_ENDPOINT=localhost:9000

  minio:
      image: minio/minio:latest@sha256:1a594faffab833866e43154c31b943d49ca1146d2c164ec3279382d7530d2ede
      volumes:
        - minio_data:/data
      ports:
        - "9000:9000"
      environment:
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio123
        - MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET=True
      command: server data

volumes:
  dbdata:
  minio_data: