version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
  caluma:
    image: projectcaluma/caluma:latest@sha256:4057ab7dd5e2ae7cda2db1180bb17691033a381872d15a07f75c98bebcbc8804
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
